"""removing enum activity from activity models

Revision ID: 38eedc94ff07
Revises: 65d4ec254eb7
Create Date: 2024-08-08 23:15:01.175938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38eedc94ff07'
down_revision: Union[str, None] = '65d4ec254eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_app_name', table_name='applications')
    op.create_index(op.f('ix_applications_app_name'), 'applications', ['app_name'], unique=False)
    op.drop_index('ix_tasks_project', table_name='tasks')
    op.create_index(op.f('ix_tasks_project'), 'tasks', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project'), table_name='tasks')
    op.create_index('ix_tasks_project', 'tasks', ['project'], unique=True)
    op.drop_index(op.f('ix_applications_app_name'), table_name='applications')
    op.create_index('ix_applications_app_name', 'applications', ['app_name'], unique=True)
    # ### end Alembic commands ###
