"""removing enum activity from activity models

Revision ID: 65d4ec254eb7
Revises: 57a1ac489f16
Create Date: 2024-08-08 23:13:51.306746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d4ec254eb7'
down_revision: Union[str, None] = '57a1ac489f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('application_id', sa.Integer(), nullable=True))
    op.drop_constraint('activities_app_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'applications', ['application_id'], ['id'])
    op.drop_column('activities', 'app')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.add_column('activities', sa.Column('app', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_app_fkey', 'activities', 'applications', ['app'], ['id'])
    op.drop_column('activities', 'application_id')
    # ### end Alembic commands ###
